name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=22.3.1
  - conda-forge::cudatoolkit=11.3.1 # cudatoolkit=11.3.1
  - pytorch::pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0 # pytorch=1.13.1
  - pytorch::torchvision=0.13.1=py310_cu113 # torchvision=0.14.1
  - numpy=1.23.5
  - pip:
      - albumentations==1.1.0
      - opencv-python==4.7.0.72
      - pudb==2019.2
      - imageio==2.14.1
      - imageio-ffmpeg==0.4.7
      - pytorch-lightning==1.5.9
      - omegaconf==2.1.1
      - test-tube>=0.7.5
      - streamlit>=0.73.1
      - setuptools==59.5.0
      - pillow==9.0.1
      - einops==0.4.1
      - torch-fidelity==0.3.0
      - transformers==4.18.0
      - torchmetrics==0.6.0
      - kornia==0.6
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e .
